language: java
jdk:
  - oraclejdk11
notifications:
  email: false
script:
  - ./gradlew build test
deploy:
  - provider: script
    script: ./gradlew publish
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./gradlew publish
    skip_cleanup: true
    on:
      tags: true
